#!/usr/bin/env python3
"""
ESTHER Mission Briefing Generator
Runs at session start to give ESTHER full context of current state.
Deploy to: ~/.openclaw/workspace/scripts/generate-briefing.py
Cron: 0 8 * * * python3 ~/.openclaw/workspace/scripts/generate-briefing.py
"""

import subprocess
import os
import json
from datetime import datetime, timezone

WORKSPACE = os.path.expanduser("~/.openclaw/workspace")
ESTHER_LAB = os.path.expanduser("~/esther-lab")
OUTPUT = os.path.join(WORKSPACE, "MISSION-BRIEF.md")

def run(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, text=True, stderr=subprocess.DEVNULL).strip()
    except:
        return "unavailable"

def get_git_log():
    return run(f"cd {ESTHER_LAB} && git log --oneline -10")

def get_open_targets():
    targets_dir = os.path.join(ESTHER_LAB, "targets")
    if not os.path.exists(targets_dir):
        return "No targets directory found"
    targets = []
    for t in os.listdir(targets_dir):
        if os.path.isdir(os.path.join(targets_dir, t)):
            targets.append(t)
    return ", ".join(targets) if targets else "No active targets"

def get_findings_summary():
    findings_dir = os.path.join(ESTHER_LAB, "findings")
    if not os.path.exists(findings_dir):
        return "No findings directory"
    summary = []
    for program in os.listdir(findings_dir):
        program_path = os.path.join(findings_dir, program)
        if os.path.isdir(program_path):
            files = os.listdir(program_path)
            summary.append(f"  - {program}/: {len(files)} files")
    return "\n".join(summary) if summary else "No findings yet"

def get_tool_status():
    tools = {
        "nmap": "nmap --version 2>&1 | head -1",
        "theHarvester": "which theHarvester 2>&1",
        "nikto": "which nikto 2>&1",
        "nuclei": "nuclei --version 2>&1 | head -1",
        "ffuf": "ffuf -V 2>&1 | head -1",
        "amass": "amass --version 2>&1 | head -1",
        "aws": "aws --version 2>&1 | head -1",
        "az": "which az 2>&1",
        "gcloud": "gcloud version 2>&1 | head -1",
        "scout": "scout --version 2>&1 | head -1",
        "metasploit": "which msfconsole 2>&1",
        "sqlmap": "sqlmap --version 2>&1 | head -1",
        "wfuzz": "which wfuzz 2>&1",
        "john": "which john 2>&1",
        "hashcat": "hashcat --version 2>&1 | head -1",
        "crackmapexec": "which crackmapexec 2>&1",
        "impacket": "which impacket-secretsdump 2>&1",
        "hydra": "which hydra 2>&1",
    }
    results = []
    for tool, cmd in tools.items():
        output = run(cmd)
        status = "✅" if output and "unavailable" not in output and "not found" not in output.lower() else "❌"
        results.append(f"  {status} {tool}: {output[:60] if output != 'unavailable' else 'not installed'}")
    return "\n".join(results)

def get_docker_status():
    return run("docker ps --format '  ✅ {{.Names}} ({{.Status}})' 2>/dev/null")

def get_soul_rules():
    soul_path = os.path.join(WORKSPACE, "SOUL.md")
    if not os.path.exists(soul_path):
        return "SOUL.md not found"
    with open(soul_path) as f:
        content = f.read()
    # Return first 500 chars as summary
    return content[:500] + "..." if len(content) > 500 else content

now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

briefing = f"""# 🦂 ESTHER MISSION BRIEF
Generated: {now}

---

## 🎯 Active Bug Bounty Targets
Program: Playtika (HackerOne — esther-lab)
Scope: *.playtika.com, *.wooga.com, *.slotomania.com, *.caesarsgames.com, *.boardkingsgame.com, *.houseoffun.com, *.bingoblitz.com, *.seriously.com, *.redecor.com, *.playwsop.com, *.playticorp.com
Out of scope: *.justfall.lol, *.justplay.lol, *.1v1.lol, *.awards.slotomania.com
Status: Phase 2 recon complete — staging/dev subdomains found but IP-whitelisted. Next: broader subdomain enumeration on remaining wildcard domains.

---

## 🔬 Lab Targets (Authorized Internal)
{get_open_targets()}

---

## 📁 Findings Summary
{get_findings_summary()}

---

## 📋 Recent Commits (esther-lab)
{get_git_log()}

---

## 🛠️ Tool Inventory
{get_tool_status()}

---

## 🐳 Docker Stack
{get_docker_status()}

---

## 📜 SOUL.md Summary
{get_soul_rules()}

---

## ⚠️ Standing Orders
- Never report success without gh api verification
- Null results are valid findings — document honestly
- All external targets require Operator Telegram approval before scanning
- Conservative rate limiting on all external targets (max 10 req/sec)
- No exploit attempts without explicit Phase 3 authorization
- Read this brief at the start of every session

---
*Brief auto-generated by generate-briefing.py — commit any updates to esther-lab*
"""

with open(OUTPUT, 'w') as f:
    f.write(briefing)

print(f"✅ Mission brief written to {OUTPUT}")
print(f"   Generated: {now}")
