#!/usr/bin/env python3
"""
hackerone-scope-fetch.py — Pull live scope from HackerOne API
Writes machine-readable scope.md to ~/esther-lab/engagements/public/<program>/

Usage:
    python3 hackerone-scope-fetch.py <program_handle>
    python3 hackerone-scope-fetch.py playtika

Environment variables required:
    H1_USERNAME     — HackerOne username (e.g. esther-lab)
    H1_API_TOKEN    — HackerOne API token

Docs: https://api.hackerone.com/customer-resources/#programs-get-program
"""

import os
import sys
import json
import requests
from datetime import datetime, timezone
from pathlib import Path

# ── Config ─────────────────────────────────────────────────────────────────────
H1_USERNAME  = os.environ.get('H1_USERNAME', 'esther-lab')
H1_API_TOKEN = os.environ.get('H1_API_TOKEN')
H1_BASE      = 'https://api.hackerone.com/v1'
ENGAGEMENTS  = Path.home() / 'esther-lab' / 'engagements' / 'public'

# ── Asset type mapping ─────────────────────────────────────────────────────────
ASSET_TYPE_LABELS = {
    'URL':            'Web / URL',
    'WILDCARD':       'Wildcard domain',
    'DOMAIN':         'Domain',
    'IP_ADDRESS':     'IP Address',
    'CIDR':           'CIDR range',
    'ANDROID_APP':    'Android App',
    'IOS_APP':        'iOS App',
    'OTHER':          'Other',
    'SOURCE_CODE':    'Source Code',
    'HARDWARE':       'Hardware',
    'SMART_CONTRACT': 'Smart Contract',
}


def h1_get(path: str) -> dict:
    """Authenticated GET to HackerOne API."""
    if not H1_API_TOKEN:
        print("❌ H1_API_TOKEN environment variable not set.")
        sys.exit(1)
    r = requests.get(
        f'{H1_BASE}{path}',
        auth=(H1_USERNAME, H1_API_TOKEN),
        headers={'Accept': 'application/json'},
        timeout=15
    )
    if r.status_code == 401:
        print("❌ HackerOne authentication failed. Check H1_USERNAME and H1_API_TOKEN.")
        sys.exit(1)
    if r.status_code == 404:
        print(f"❌ Program not found: {path}")
        sys.exit(1)
    r.raise_for_status()
    return r.json()


def fetch_program_info(handle: str) -> dict:
    """Fetch basic program metadata."""
    data = h1_get(f'/programs/{handle}')
    return data.get('attributes', {})


def fetch_structured_scopes(handle: str) -> tuple[list, list]:
    """
    Fetch structured scopes, return (in_scope, out_of_scope).
    Paginates automatically.
    """
    in_scope     = []
    out_of_scope = []
    page         = 1

    while True:
        data = h1_get(f'/programs/{handle}/structured_scopes?page[number]={page}&page[size]=100')
        items = data.get('data', [])
        if not items:
            break

        for item in items:
            attrs = item.get('attributes', {})
            entry = {
                'asset_type':        attrs.get('asset_type', 'OTHER'),
                'asset_identifier':  attrs.get('asset_identifier', ''),
                'eligible_for_bounty': attrs.get('eligible_for_bounty', False),
                'eligible_for_submission': attrs.get('eligible_for_submission', True),
                'instruction':       attrs.get('instruction', ''),
                'max_severity':      attrs.get('max_severity', 'critical'),
            }
            if attrs.get('eligible_for_submission', True):
                in_scope.append(entry)
            else:
                out_of_scope.append(entry)

        # Check for more pages
        links = data.get('links', {})
        if not links.get('next'):
            break
        page += 1

    return in_scope, out_of_scope


def write_scope_md(handle: str, program_info: dict, in_scope: list, out_of_scope: list):
    """Write machine-readable scope.md."""
    eng_dir = ENGAGEMENTS / handle
    eng_dir.mkdir(parents=True, exist_ok=True)
    (eng_dir / 'findings').mkdir(exist_ok=True)

    scope_path = eng_dir / 'scope.md'
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')

    # Group in-scope by asset type
    grouped: dict[str, list] = {}
    for entry in in_scope:
        t = entry['asset_type']
        grouped.setdefault(t, []).append(entry)

    # Group out-of-scope
    oos_grouped: dict[str, list] = {}
    for entry in out_of_scope:
        t = entry['asset_type']
        oos_grouped.setdefault(t, []).append(entry)

    lines = [
        f"# Scope: {handle}",
        f"<!-- AUTO-GENERATED by hackerone-scope-fetch.py — DO NOT EDIT MANUALLY -->",
        f"<!-- Last fetched: {now} -->",
        f"",
        f"## Program",
        f"",
        f"- **Handle:** {handle}",
        f"- **Platform:** HackerOne",
        f"- **H1 URL:** https://hackerone.com/{handle}",
        f"- **Fetched:** {now}",
        f"",
        f"---",
        f"",
        f"## IN SCOPE",
        f"",
    ]

    for asset_type, entries in sorted(grouped.items()):
        label = ASSET_TYPE_LABELS.get(asset_type, asset_type)
        lines.append(f"### {label}")
        lines.append("")
        for e in sorted(entries, key=lambda x: x['asset_identifier']):
            bounty_tag = " 💰" if e['eligible_for_bounty'] else ""
            severity   = e['max_severity'].upper() if e['max_severity'] else 'CRITICAL'
            lines.append(f"- `{e['asset_identifier']}`{bounty_tag} — max severity: {severity}")
            if e['instruction']:
                lines.append(f"  - Note: {e['instruction'].strip()}")
        lines.append("")

    lines += [
        "---",
        "",
        "## OUT OF SCOPE",
        "",
        "> ⚠️  ESTHER must never scan or interact with these assets.",
        "",
    ]

    if oos_grouped:
        for asset_type, entries in sorted(oos_grouped.items()):
            label = ASSET_TYPE_LABELS.get(asset_type, asset_type)
            lines.append(f"### {label}")
            lines.append("")
            for e in sorted(entries, key=lambda x: x['asset_identifier']):
                lines.append(f"- `{e['asset_identifier']}`")
            lines.append("")
    else:
        lines.append("_(none explicitly listed — apply conservative judgment)_")
        lines.append("")

    lines += [
        "---",
        "",
        "## ESTHER OPERATING RULES FOR THIS ENGAGEMENT",
        "",
        "- Max rate: **10 req/sec** on all active scanning",
        "- Phase 1 (passive recon): ✅ Authorized — no approval needed",
        "- Phase 2 (active scanning — nmap, nuclei, ffuf): ⏳ Request Operator approval per domain",
        "- Phase 3 (exploitation): ⏳ Request Operator approval per finding",
        "- Always commit findings to `engagements/public/{}/findings/` and verify with `gh api`".format(handle),
        "- Never scan OUT OF SCOPE assets under any circumstances",
        "- Null results are valid findings — document honestly",
        "",
        "---",
        "",
        f"_Generated by hackerone-scope-fetch.py · {now}_",
    ]

    scope_path.write_text('\n'.join(lines))
    print(f"  ✅ Scope written to: {scope_path}")
    print(f"     In scope:     {len(in_scope)} assets")
    print(f"     Out of scope: {len(out_of_scope)} assets")
    return scope_path


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 hackerone-scope-fetch.py <program_handle>")
        print("   eg: python3 hackerone-scope-fetch.py playtika")
        sys.exit(1)

    handle = sys.argv[1].lower().strip()
    print(f"🦂 Fetching live scope for: {handle}")

    program_info          = fetch_program_info(handle)
    in_scope, out_of_scope = fetch_structured_scopes(handle)
    scope_path            = write_scope_md(handle, program_info, in_scope, out_of_scope)

    print()
    print(f"  Run load-scope.py to activate this scope for ESTHER:")
    print(f"  python3 ~/.openclaw/workspace/scripts/load-scope.py {handle}")


if __name__ == '__main__':
    main()
